### ISSUE TITLE
Glitching default spawns

### ISSUE THREAD

**Issue by 017** [probe4aiur/PlayerPreferences#5]
Started seeing issues when I added this plugin to my server - seems that if people don't have preferences made for the plugin it will spawn people with preferences seperately from people who don't. May be related to prefs_distribute_all.

**Comment by 017** [comment]
Anyone with no preferences seems to not spawn for NTF or chaos waves vs. people who do.

**Comment by 017** [comment]
Oh is that what that does? I had it on because I thought it was something with enabling the weighting for everyone even if they don't have preferences set. I'll turn it off and see if any mishaps occur.

**Comment by 017** [comment]
Worked fine once that got turned off, so all's well.

**Comment by probe4aiur** [comment]
Yes, weighting only affects those with preferences. If you want just weights, use smart class picker.
